[sui]

[sui.reports]
base_url = "http://reportes.sui.gov.co/fabricaReportes/reporte"

[sui.reports.TC1_certified]
url = "https://sui.superservicios.gov.co/Reportes-del-sector/Energia/Reportes-comerciales/Informacion-del-Formato-TC1-Certificado-Para-Validar-los-formatos-TC2-y-TC6-Res-SSPD-20192200020155-del-25-06-2019"
idreporte = "ele_com_133"
ele_com_133.agno = 2024
ele_com_133.comercializador = "59850"
ele_com_133.periodo = 1
formatting_chosenformat = "CSV"
integration_masterreport = "ele_com_133"

[sui.reports.usage]
url = "https://sui.superservicios.gov.co/Reportes-del-sector/Energia/Reportes-comerciales/Consolidado-Energia-por-Empresa-Departamento-y-Municipio"

[sui.reports.usage.default_params]
integration_masterreport = "ele_com_096"
formatting_chosenformat = "CSV"
idreporte = "ele_com_096"
ele_com_096.agno = "2015"
ele_com_096.periodo = "1"
ele_com_096.ubic = "1"
ele_com_096.depto = "NULL_VALUE"
ele_com_096.municipio = "NULL_VALUE"
ele_com_096.empresa = "NULL_VALUE"
ele_com_096.valor = "3"
