GET http://reportes.sui.gov.co/fabricaReportes/reporte
    ?integration_masterreport=ele_com_132
    &reporte_timesaccesed=3
    &statistics_idvisita=3624382
    &caching_actualrequest=ele_com_132078260677D31109220D1B059485A68BE20240224084848888
    &paginacion_page=1
    &paginacion_size=-1
    &ordering_orderby=
    &ordering_ordermode=
    &formatting_chosenformat=HTML
    &graphics_graphic=0
    &idreporte=ele_com_132
    &sizeChooser=-1
    &nombre_agno=2024
    &ele_com_132.agno=2024
    &nombre_periodo=Enero
    &ele_com_132.periodo=1
    &nombre_comercializador=ENERBIT+SAS+ESP
    &ele_com_132.comercializador=59850